-- AlterTable
ALTER TABLE "VM" ADD COLUMN "sshHost" TEXT;
ALTER TABLE "VM" ADD COLUMN "sshKeyPath" TEXT;
ALTER TABLE "VM" ADD COLUMN "sshPassword" TEXT;
ALTER TABLE "VM" ADD COLUMN "sshPort" INTEGER;
ALTER TABLE "VM" ADD COLUMN "sshUser" TEXT;
